;;; tidal-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from tidal.el

(autoload 'tidal-start-haskell "tidal" "\
Start haskell." t)
(defalias 'run-tidal #'tidal-start-haskell "\
Start tidal in the haskell interpreter.")
(autoload 'literate-tidal-mode "tidal" "\
Major mode for interacting with an inferior haskell process.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.ltidal\\'" . literate-tidal-mode))
(autoload 'tidal-mode "tidal" "\
Major mode for interacting with an inferior haskell process.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.tidal\\'" . tidal-mode))
(register-definition-prefixes "tidal" '("tidal-"))

;;; End of scraped data

(provide 'tidal-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; tidal-autoloads.el ends here
