;;; copilot-chat-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from copilot-chat-command.el

(autoload 'copilot-chat-ask-and-insert "copilot-chat-command" "\
Send to Copilot a custom prompt and insert answer in current buffer at point." t)
(autoload 'copilot-chat-explain "copilot-chat-command" "\
Ask Copilot to explain the current selected code." t)
(autoload 'copilot-chat-review "copilot-chat-command" "\
Ask Copilot to review the current selected code." t)
(autoload 'copilot-chat-doc "copilot-chat-command" "\
Ask Copilot to write documentation for the current selected code." t)
(autoload 'copilot-chat-fix "copilot-chat-command" "\
Ask Copilot to fix the current selected code." t)
(autoload 'copilot-chat-optimize "copilot-chat-command" "\
Ask Copilot to optimize the current selected code." t)
(autoload 'copilot-chat-test "copilot-chat-command" "\
Ask Copilot to generate test for the current selected code." t)
(autoload 'copilot-chat-explain-symbol-at-line "copilot-chat-command" "\
Ask Copilot to explain symbol under point.
Given the code line as background info." t)
(autoload 'copilot-chat-explain-defun "copilot-chat-command" "\
Mark current function definition and ask Copilot to explain it, then unmark." t)
(autoload 'copilot-chat-custom-prompt-function "copilot-chat-command" "\
Mark current function and ask copilot-chat with custom prompt." t)
(autoload 'copilot-chat-review-whole-buffer "copilot-chat-command" "\
Mark whole buffer, ask Copilot to review it, then unmark.
It can be used to review the magit diff for my change, or other people's" t)
(autoload 'copilot-chat-switch-to-buffer "copilot-chat-command" "\
Switch to Copilot Chat buffer.
Side by side with the current code editing buffer." t)
(autoload 'copilot-chat-custom-prompt-selection "copilot-chat-command" "\
Send to Copilot a custom prompt followed by the current selected code/buffer.
If CUSTOM-PROMPT is provided, use it instead of reading from the mini-buffer.

(fn &optional CUSTOM-PROMPT)" t)
(autoload 'copilot-chat-custom-prompt-mini-buffer "copilot-chat-command" "\
Read a string with Helm completion, showing historical inputs." t)
(autoload 'copilot-chat-list "copilot-chat-command" "\
Open Copilot Chat list buffer." t)
(autoload 'copilot-chat-display "copilot-chat-command" "\
Display copilot chat buffer.
With prefix argument, explicitly ask for which instance to use.
Optional argument ARG if non-nil, force instance selection.

(fn &optional ARG)" t)
(autoload 'copilot-chat-hide "copilot-chat-command" "\
Hide copilot chat buffer." t)
(autoload 'copilot-chat-insert-commit-message "copilot-chat-command" "\
Generate and insert a commit message using Copilot.
Uses the current staged changes in git
to generate an appropriate commit message.
Requires the repository to have staged changes." t)
(autoload 'copilot-chat-set-model "copilot-chat-command" "\
Set the Copilot Chat model to MODEL.
Fetches available models from the API if not already fetched.

(fn MODEL)" t)
(autoload 'copilot-chat-clear-auth-cache "copilot-chat-command" "\
Clear the auth cache for Copilot Chat." t)
(autoload 'copilot-chat-reset-models "copilot-chat-command" "\
Reset model cache and fetch models again.
This is useful when GitHub adds new models or updates model capabilities.
Clears model cache from memory and disk, then triggers background fetch." t)
(register-definition-prefixes "copilot-chat-command" '("copilot-chat-"))


;;; Generated autoloads from copilot-chat-common.el

(register-definition-prefixes "copilot-chat-common" '("copilot-chat-"))


;;; Generated autoloads from copilot-chat-copilot.el

(register-definition-prefixes "copilot-chat-copilot" '("copilot-chat-"))


;;; Generated autoloads from copilot-chat-curl.el

(register-definition-prefixes "copilot-chat-curl" '("copilot-chat-"))


;;; Generated autoloads from copilot-chat-frontend.el

(register-definition-prefixes "copilot-chat-frontend" '("copilot-chat-"))


;;; Generated autoloads from copilot-chat-instance.el

(autoload 'copilot-chat-kill-instance "copilot-chat-instance" "\
Interactively kill a selected copilot chat instance.
All its associated buffers are killed." t)
(register-definition-prefixes "copilot-chat-instance" '("copilot-chat--"))


;;; Generated autoloads from copilot-chat-markdown.el

(register-definition-prefixes "copilot-chat-markdown" '("copilot-chat-" "poly-copilot-markdown-"))


;;; Generated autoloads from copilot-chat-org.el

(register-definition-prefixes "copilot-chat-org" '("copilot-chat-" "poly-copilot-org-"))


;;; Generated autoloads from copilot-chat-prompt-mode.el

(register-definition-prefixes "copilot-chat-prompt-mode" '("copilot-chat-"))


;;; Generated autoloads from copilot-chat-prompts.el

(register-definition-prefixes "copilot-chat-prompts" '("copilot-chat-"))


;;; Generated autoloads from copilot-chat-request.el

(register-definition-prefixes "copilot-chat-request" '("copilot-chat--"))


;;; Generated autoloads from copilot-chat-shell-maker.el

(register-definition-prefixes "copilot-chat-shell-maker" '("copilot-chat--shell"))


;;; Generated autoloads from copilot-chat-transient.el

 (autoload 'copilot-chat-transient "copilot-chat" nil t)
 (autoload 'copilot-chat-transient-buffers "copilot-chat" nil t)
 (autoload 'copilot-chat-transient-code "copilot-chat" nil t)

;;; End of scraped data

(provide 'copilot-chat-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; copilot-chat-autoloads.el ends here
