;;; copilot-chat-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from copilot-chat.el

(autoload 'copilot-chat-ask-and-insert "copilot-chat" "\
Send to Copilot a custom prompt and insert answer in current buffer at point." t)
(autoload 'copilot-chat-explain "copilot-chat" "\
Ask Copilot to explain the current selected code." t)
(autoload 'copilot-chat-review "copilot-chat" "\
Ask Copilot to review the current selected code." t)
(autoload 'copilot-chat-doc "copilot-chat" "\
Ask Copilot to write documentation for the current selected code." t)
(autoload 'copilot-chat-fix "copilot-chat" "\
Ask Copilot to fix the current selected code." t)
(autoload 'copilot-chat-optimize "copilot-chat" "\
Ask Copilot to optimize the current selected code." t)
(autoload 'copilot-chat-test "copilot-chat" "\
Ask Copilot to generate tests for the current selected code." t)
(autoload 'copilot-chat-custom-prompt-selection "copilot-chat" "\
Send to Copilot a custom prompt followed by the current selected code." t)
(autoload 'copilot-chat-list "copilot-chat" "\
Open Copilot Chat list buffer." t)
(autoload 'copilot-chat-display "copilot-chat" "\
Display copilot chat buffers." t)
(register-definition-prefixes "copilot-chat" '("copilot-chat"))


;;; Generated autoloads from copilot-chat-common.el

(register-definition-prefixes "copilot-chat-common" '("copilot-chat-"))


;;; Generated autoloads from copilot-chat-copilot.el

(register-definition-prefixes "copilot-chat-copilot" '("copilot-chat-"))


;;; Generated autoloads from copilot-chat-curl.el

(register-definition-prefixes "copilot-chat-curl" '("copilot-chat-"))


;;; Generated autoloads from copilot-chat-markdown.el

(register-definition-prefixes "copilot-chat-markdown" '("copilot-chat--markdown-format-data"))


;;; Generated autoloads from copilot-chat-request.el

(register-definition-prefixes "copilot-chat-request" '("copilot-chat--request-ask"))


;;; Generated autoloads from copilot-chat-shell-maker.el

(register-definition-prefixes "copilot-chat-shell-maker" '("copilot-chat-"))

;;; End of scraped data

(provide 'copilot-chat-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; copilot-chat-autoloads.el ends here
